package base.sp;

import java.util.LinkedHashMap;

public class CommonList {
	public static LinkedHashMap<String,String> province() {
		LinkedHashMap<String,String> list=new LinkedHashMap<String,String>();
		list.put("AG","Agrigento");
		list.put("AL","Alessandria");
		list.put("AN","Ancona");
		list.put("AO","Aosta");
		list.put("AQ","l'Aquila");
		list.put("AR","Arezzo");
		list.put("AP","Ascoli Piceno");
		list.put("AT","Asti");
		list.put("AV","Avellino");
		list.put("BA","Bari");
		list.put("BT","Barletta-Andria-Trani");
		list.put("BL","Belluno");
		list.put("BN","Benevento");
		list.put("BG","Bergamo");
		list.put("BI","Biella");
		list.put("BO","Bologna");
		list.put("BZ","Bolzano");
		list.put("BS","Brescia");
		list.put("BR","Brindisi");
		list.put("CA","Cagliari");
		list.put("CL","Caltanissetta");
		list.put("CB","Campobasso");
		list.put("CI","Carbonia-Iglesias");
		list.put("CE","Caserta");
		list.put("CT","Catania");
		list.put("CZ","Catanzaro");
		list.put("CH","Chieti");
		list.put("CO","Como");
		list.put("CS","Cosenza");
		list.put("CR","Cremona");
		list.put("KR","Crotone");
		list.put("CN","Cuneo");
		list.put("EN","Enna");
		list.put("FM","Fermo");
		list.put("FE","Ferrara");
		list.put("FI","Firenze");
		list.put("FG","Foggia");
		list.put("FC","Forli-Cesena");
		list.put("FR","Frosinone");
		list.put("GE","Genova");
		list.put("GO","Gorizia");
		list.put("GR","Grosseto");
		list.put("IM","Imperia");
		list.put("IS","Isernia");
		list.put("SP","La spezia");
		list.put("LT","Latina");
		list.put("LE","Lecce");
		list.put("LC","Lecco");
		list.put("LI","Livorno");
		list.put("LO","Lodi");
		list.put("LU","Lucca");
		list.put("MC","Macerata");
		list.put("MN","Mantova");
		list.put("MS","Massa-Carrara");
		list.put("MT","Matera");
		list.put("VS","Medio Campidano");
		list.put("ME","Messina");
		list.put("MI","Milano");
		list.put("MO","Modena");
		list.put("MB","Monza e della Brianza");
		list.put("NA","Napoli");
		list.put("NO","Novara");
		list.put("NU","Nuoro");
		list.put("OG","Ogliastra");
		list.put("OT","Olbia-Tempio");
		list.put("OR","Oristano");
		list.put("PD","Padova");
		list.put("PA","Palermo");
		list.put("PR","Parma");
		list.put("PV","Pavia");
		list.put("PG","Perugia");
		list.put("PU","Pesaro-Urbino");
		list.put("PE","Pescara");
		list.put("PC","Piacenza");
		list.put("PI","Pisa");
		list.put("PT","Pistoia");
		list.put("PN","Pordenone");
		list.put("PZ","Potenza");
		list.put("PO","Prato");
		list.put("RG","Ragusa");
		list.put("RA","Ravenna");
		list.put("RC","Reggio-Calabria");
		list.put("RE","Reggio-Emilia");
		list.put("RI","Rieti");
		list.put("RN","Rimini");
		list.put("RM","Roma");
		list.put("RO","Rovigo");
		list.put("SA","Salerno");
		list.put("SS","Sassari");
		list.put("SV","Savona");
		list.put("SI","Siena");
		list.put("SR","Siracusa");
		list.put("SO","Sondrio");
		list.put("TA","Taranto");
		list.put("TE","Teramo");
		list.put("TR","Terni");
		list.put("TO","Torino");
		list.put("TP","Trapani");
		list.put("TN","Trento");
		list.put("TV","Treviso");
		list.put("TS","Trieste");
		list.put("UD","Udine");
		list.put("VA","Varese");
		list.put("VE","Venezia");
		list.put("VB","Verbano-Cusio-Ossola");
		list.put("VC","Vercelli");
		list.put("VR","Verona");
		list.put("VV","Vibo-Valentia");
		list.put("VI","Vicenza");
		list.put("VT","Viterbo");;
		return list;
		}

public static LinkedHashMap<String,String> nazioni()
{
LinkedHashMap<String,String> list=new LinkedHashMap<String,String>();
list.put("AF","Afghanistan");
list.put("AX","&Aring;land Islands");
list.put("AL","Albania");
list.put("DZ","Algeria");
list.put("AS","American Samoa");
list.put("AD","Andorra");
list.put("AO","Angola");
list.put("AI","Anguilla");
list.put("AQ","Antarctica");
list.put("AG","Antigua and Barbuda");
list.put("AR","Argentina");
list.put("AM","Armenia");
list.put("AW","Aruba");
list.put("AU","Australia");
list.put("AT","Austria");
list.put("AZ","Azerbaijan");
list.put("BS","Bahamas");
list.put("BH","Bahrain");
list.put("BD","Bangladesh");
list.put("BB","Barbados");
list.put("BY","Belarus");
list.put("BE","Belgium");
list.put("BZ","Belize");
list.put("BJ","Benin");
list.put("BM","Bermuda");
list.put("BT","Bhutan");
list.put("BO","Bolivia, Plurinational State of");
list.put("BA","Bosnia and Herzegovina");
list.put("BW","Botswana");
list.put("BV","Bouvet Island");
list.put("BR","Brazil");
list.put("IO","British Indian Ocean Territory");
list.put("BN","Brunei Darussalam");
list.put("BG","Bulgaria");
list.put("BF","Burkina Faso");
list.put("BI","Burundi");
list.put("KH","Cambodia");
list.put("CM","Cameroon");
list.put("CA","Canada");
list.put("CV","Cape Verde");
list.put("KY","Cayman Islands");
list.put("CF","Central African Republic");
list.put("TD","Chad");
list.put("CL","Chile");
list.put("CN","China");
list.put("CX","Christmas Island");
list.put("CC","Cocos (Keeling) Islands");
list.put("CO","Colombia");
list.put("KM","Comoros");
list.put("CG","Congo");
list.put("CD","Congo, the Democratic Republic of the");
list.put("CK","Cook Islands");
list.put("CR","Costa Rica");
list.put("CI","C&ocirc;te d'Ivoire");
list.put("HR","Croatia");
list.put("CU","Cuba");
list.put("CY","Cyprus");
list.put("CZ","Czech Republic");
list.put("DK","Denmark");
list.put("DJ","Djibouti");
list.put("DM","Dominica");
list.put("DO","Dominican Republic");
list.put("EC","Ecuador");
list.put("EG","Egypt");
list.put("SV","El Salvador");
list.put("GQ","Equatorial Guinea");
list.put("ER","Eritrea");
list.put("EE","Estonia");
list.put("ET","Ethiopia");
list.put("FK","Falkland Islands (Malvinas)");
list.put("FO","Faroe Islands");
list.put("FJ","Fiji");
list.put("FI","Finland");
list.put("FR","France");
list.put("GF","French Guiana");
list.put("PF","French Polynesia");
list.put("TF","French Southern Territories");
list.put("GA","Gabon");
list.put("GM","Gambia");
list.put("GE","Georgia");
list.put("DE","Germany");
list.put("GH","Ghana");
list.put("GI","Gibraltar");
list.put("GR","Greece");
list.put("GL","Greenland");
list.put("GD","Grenada");
list.put("GP","Guadeloupe");
list.put("GU","Guam");
list.put("GT","Guatemala");
list.put("GG","Guernsey");
list.put("GN","Guinea");
list.put("GW","Guinea-Bissau");
list.put("GY","Guyana");
list.put("HT","Haiti");
list.put("HM","Heard Island and McDonald Islands");
list.put("VA","Holy See (Vatican City State)");
list.put("HN","Honduras");
list.put("HK","Hong Kong");
list.put("HU","Hungary");
list.put("IS","Iceland");
list.put("IN","India");
list.put("ID","Indonesia");
list.put("IR","Iran, Islamic Republic of");
list.put("IQ","Iraq");
list.put("IE","Ireland");
list.put("IM","Isle of Man");
list.put("IL","Israel");
list.put("IT","Italy");
list.put("JM","Jamaica");
list.put("JP","Japan");
list.put("JE","Jersey");
list.put("JO","Jordan");
list.put("KZ","Kazakhstan");
list.put("KE","Kenya");
list.put("KI","Kiribati");
list.put("KP","Korea, Democratic People's Republic of");
list.put("KR","Korea, Republic of");
list.put("KW","Kuwait");
list.put("KG","Kyrgyzstan");
list.put("LA","Lao People's Democratic Republic");
list.put("LV","Latvia");
list.put("LB","Lebanon");
list.put("LS","Lesotho");
list.put("LR","Liberia");
list.put("LY","Libyan Arab Jamahiriya");
list.put("LI","Liechtenstein");
list.put("LT","Lithuania");
list.put("LU","Luxembourg");
list.put("MO","Macao");
list.put("MK","Macedonia, the former Yugoslav Republic of");
list.put("MG","Madagascar");
list.put("MW","Malawi");
list.put("MY","Malaysia");
list.put("MV","Maldives");
list.put("ML","Mali");
list.put("MT","Malta");
list.put("MH","Marshall Islands");
list.put("MQ","Martinique");
list.put("MR","Mauritania");
list.put("MU","Mauritius");
list.put("YT","Mayotte");
list.put("MX","Mexico");
list.put("FM","Micronesia, Federated States of");
list.put("MD","Moldova, Republic of");
list.put("MC","Monaco");
list.put("MN","Mongolia");
list.put("ME","Montenegro");
list.put("MS","Montserrat");
list.put("MA","Morocco");
list.put("MZ","Mozambique");
list.put("MM","Myanmar");
list.put("NA","Namibia");
list.put("NR","Nauru");
list.put("NP","Nepal");
list.put("NL","Netherlands");
list.put("AN","Netherlands Antilles");
list.put("NC","New Caledonia");
list.put("NZ","New Zealand");
list.put("NI","Nicaragua");
list.put("NE","Niger");
list.put("NG","Nigeria");
list.put("NU","Niue");
list.put("NF","Norfolk Island");
list.put("MP","Northern Mariana Islands");
list.put("NO","Norway");
list.put("OM","Oman");
list.put("PK","Pakistan");
list.put("PW","Palau");
list.put("PS","Palestinian Territory, Occupied");
list.put("PA","Panama");
list.put("PG","Papua New Guinea");
list.put("PY","Paraguay");
list.put("PE","Peru");
list.put("PH","Philippines");
list.put("PN","Pitcairn");
list.put("PL","Poland");
list.put("PT","Portugal");
list.put("PR","Puerto Rico");
list.put("QA","Qatar");
list.put("RE","R&eacute;union");
list.put("RO","Romania");
list.put("RU","Russian Federation");
list.put("RW","Rwanda");
list.put("BL","Saint Barth&eacute;lemy");
list.put("SH","Saint Helena, Ascension and Tristan da Cunha");
list.put("KN","Saint Kitts and Nevis");
list.put("LC","Saint Lucia");
list.put("MF","Saint Martin (French part)");
list.put("PM","Saint Pierre and Miquelon");
list.put("VC","Saint Vincent and the Grenadines");
list.put("WS","Samoa");
list.put("SM","San Marino");
list.put("ST","Sao Tome and Principe");
list.put("SA","Saudi Arabia");
list.put("SN","Senegal");
list.put("RS","Serbia");
list.put("SC","Seychelles");
list.put("SL","Sierra Leone");
list.put("SG","Singapore");
list.put("SK","Slovakia");
list.put("SI","Slovenia");
list.put("SB","Solomon Islands");
list.put("SO","Somalia");
list.put("ZA","South Africa");
list.put("GS","South Georgia and the South Sandwich Islands");
list.put("ES","Spain");
list.put("LK","Sri Lanka");
list.put("SD","Sudan");
list.put("SR","Suriname");
list.put("SJ","Svalbard and Jan Mayen");
list.put("SZ","Swaziland");
list.put("SE","Sweden");
list.put("CH","Switzerland");
list.put("SY","Syrian Arab Republic");
list.put("TW","Taiwan, Province of China");
list.put("TJ","Tajikistan");
list.put("TZ","Tanzania, United Republic of");
list.put("TH","Thailand");
list.put("TL","Timor-Leste");
list.put("TG","Togo");
list.put("TK","Tokelau");
list.put("TO","Tonga");
list.put("TT","Trinidad and Tobago");
list.put("TN","Tunisia");
list.put("TR","Turkey");
list.put("TM","Turkmenistan");
list.put("TC","Turks and Caicos Islands");
list.put("TV","Tuvalu");
list.put("UG","Uganda");
list.put("UA","Ukraine");
list.put("AE","United Arab Emirates");
list.put("GB","United Kingdom");
list.put("US","United States");
list.put("UM","United States Minor Outlying Islands");
list.put("UY","Uruguay");
list.put("UZ","Uzbekistan");
list.put("VU","Vanuatu");
list.put("VE","Venezuela, Bolivarian Republic of");
list.put("VN","Viet Nam");
list.put("VG","Virgin Islands, British");
list.put("VI","Virgin Islands, U.S.");
list.put("WF","Wallis and Futuna");
list.put("EH","Western Sahara");
list.put("YE","Yemen");
list.put("ZM","Zambia");
list.put("ZW","Zimbabwe");
return list;
}

}
